package com.boku.pojo;

public class CartBook {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart_book.book_id
     *
     * @mbg.generated
     */
    private Integer bookId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart_book.number
     *
     * @mbg.generated
     */
    private Integer number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart_book.cart_id
     *
     * @mbg.generated
     */
    private Integer cartId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart_book.book_id
     *
     * @return the value of cart_book.book_id
     *
     * @mbg.generated
     */
    public Integer getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart_book.book_id
     *
     * @param bookId the value for cart_book.book_id
     *
     * @mbg.generated
     */
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart_book.number
     *
     * @return the value of cart_book.number
     *
     * @mbg.generated
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart_book.number
     *
     * @param number the value for cart_book.number
     *
     * @mbg.generated
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart_book.cart_id
     *
     * @return the value of cart_book.cart_id
     *
     * @mbg.generated
     */
    public Integer getCartId() {
        return cartId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart_book.cart_id
     *
     * @param cartId the value for cart_book.cart_id
     *
     * @mbg.generated
     */
    public void setCartId(Integer cartId) {
        this.cartId = cartId;
    }
}