package com.boku.mapper;

import java.util.List;
import java.util.Map;

import com.boku.pojo.Book;
import com.boku.pojo.BookTypeCount;

public interface BookMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated
     */
    int insert(Book record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated
     */
    int insertSelective(Book record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated
     */
    Book selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Book record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Book record);
    
    List<Book> getBookListByIds(List<Integer> ids);

	List<Book> selectBookByKeywords(Map<String, Object> params);
    
    List<Book> getBookList();
    
    List<Book> getNewBookList();
    
    List<Book> getHotBookList();
    
    List<BookTypeCount> getHotBookAndCountList();
    
    List<Book> getBookOrderByPurchaseCount(Integer type,Integer priceMin, Integer priceMax);
    
    List<Book> getBookOrderByTime(Integer type,Integer priceMin, Integer priceMax);
}