package com.boku.mapper;

import com.boku.pojo.CartBook;

public interface CartBookMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart_book
     *
     * @mbg.generated
     */
    int insert(CartBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart_book
     *
     * @mbg.generated
     */
    int insertSelective(CartBook record);
}