package com.boku.mapper;

import com.boku.pojo.OrderBook;

public interface OrderBookMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_book
     *
     * @mbg.generated
     */
    int insert(OrderBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_book
     *
     * @mbg.generated
     */
    int insertSelective(OrderBook record);
}