package com.boku.mapper;

import java.util.List;

import com.boku.pojo.OrderBook;
import com.boku.pojo.UserCart;

public interface OrderBookMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_book
     *
     * @mbg.generated
     */
    int insert(List<OrderBook> orderBooks);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_book
     *
     * @mbg.generated
     */
    int insertSelective(OrderBook record);

	List<UserCart> selectOrderDetail(Integer orderId);
}